# This is a basic workflow to help you get started with Actions

name: Notify New Issues

# Controls when the workflow will run
on:
  # Triggers the workflow on comment events on pending response issues
  issues:
    types: [opened]

# Limit the GITHUB_TOKEN permissions
permissions: {}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "notify"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run webhook curl command
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_ISSUE_WEBHOOK_URL }}
          ISSUE: ${{toJson(github.event.issue.title)}}
          ISSUE_URL: ${{github.event.issue.html_url}}
          USER: ${{github.event.issue.user.login}}
        shell: bash
        run: echo $ISSUE | sed 's/[^a-zA-Z0-9 &().,:]//g' | xargs -I {} curl -s POST "$WEBHOOK_URL" -H "Content-Type:application/json" --data '{"issue":"{}", "issueUrl":"'$ISSUE_URL'", "user":"'$USER'"}'
